version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/api
    command: bash -c "pipenv run python3 apps/incidentes/backend/app.py"
