version: '3'

services:
  api-flask:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/api
    command: bash -c "pipenv run python3 apps/incidents/backend_flask/run.py"

  api-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/api
    command: bash -c "pipenv run python3 apps/incidents/backend_fastapi/run.py"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - "5672:5672"
        - "15672:15672"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
