version: '3'

services:
  api-flask:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/api
    command: bash -c "pipenv run uvicorn apps.incidentes.backend_flask.app:app --host 0.0.0.0 --port 5000 --reload"

  api-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/api
    command: bash -c "pipenv run uvicorn apps.incidentes.backend_fastapi.app:app --host 0.0.0.0 --port 8000 --reload"
#    command: bash -c "pipenv run apps/incidentes/backend_fastapi/run.sh"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - "5672:5672"
        - "15672:15672"
