
[tool.pytest.ini_options]
pythonpath = ["src"]
python_files = ["Test*.py", "test_*.py"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true

