
mongodb:
  username: ${MONGO_USERNAME}
  password: ${MONGO_PASSWORD}
  host: ${MONGO_HOST}
  port: ${MONGO_PORT}

rabbit_mq:
  host: ${RABBIT_MQ_HOST}
  port: ${RABBIT_MQ_PORT}
  username: ${RABBIT_MQ_USERNAME}
  password: ${RABBIT_MQ_PASSWORD}
  virtual_host: ${RABBIT_MQ_VIRTUAL_HOST}

aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  account_id: ${AWS_ACCOUNT_ID}

app:
  company_name: ${APP_COMPANY_NAME}
  event_bus_exchange_name: ${APP_EVENT_BUS_EXCHANGE_NAME}
  consume_event_interval: ${APP_CONSUME_EVENT_INTERVAL}
  consume_event_max_retries: ${APP_CONSUME_EVENT_MAX_RETRIES}
  consume_event_retry_interval: ${APP_CONSUME_EVENT_RETRY_INTERVAL}
